export type AppCommand =
  | 'focus-capture'
  | 'capture-clipboard'
  | 'focus-search'
  | 'save-note'
  | 'analyze-note'
  | 'export-markdown'
  | 'export-mcp-handoff'
  | 'export-finetune-dataset'
  | 'import-library'
  | 'export-library'
  | 'export-library-markdown'
  | 'toggle-settings'
  | 'view-note'
  | 'view-plan'
  | 'view-network'
