export type AppCommand =
  | 'focus-capture'
  | 'focus-search'
  | 'save-note'
  | 'analyze-note'
  | 'export-markdown'
  | 'import-library'
  | 'export-library'
  | 'toggle-settings'
  | 'view-note'
  | 'view-network'
